import { hash, genSalt } from "bcrypt";
import { nanoid } from "nanoid";

async function superAdmin(prisma) {
  const salt = await genSalt(10);
  const password = await hash("Appblocks@123", salt);

  await prisma.admin_users.createMany({
    data: [
      // {
      //   id: nanoid(),
      //   full_name: "Test User 1",
      //   user_name: "test1",
      //   email: "test1@mailinator.com",
      //   password: password,
      //   role: "admin",
      //   is_verified: false,
      //   created_at: new Date(),
      //   updated_at: new Date(),
      // },
      // {
      //   id: nanoid(),
      //   full_name: "Test User 2",
      //   user_name: "test2",
      //   email: "test2@mailinator.com",
      //   password: password,
      //   role: "admin",
      //   is_verified: false,
      //   created_at: new Date(),
      //   updated_at: new Date(),
      // },
      // {
      //   id: nanoid(),
      //   full_name: "Test User 3",
      //   user_name: "test3",
      //   email: "test3@mailinator.com",
      //   password: password,
      //   role: "admin",
      //   is_verified: false,
      //   created_at: new Date(),
      //   updated_at: new Date(),
      // },
      // {
      //   id: nanoid(),
      //   full_name: "Test User 4",
      //   user_name: "test4",
      //   email: "test4@mailinator.com",
      //   password: password,
      //   role: "admin",
      //   is_verified: false,
      //   created_at: new Date(),
      //   updated_at: new Date(),
      // },
      {
        id: nanoid(),
        full_name: "Jishnu N Bhattathiri",
        user_name: "jishnu",
        email: "jishnu.nb@mailinator.com",
        password: password,
        role: "admin",
        is_verified: false,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: nanoid(),
        full_name: "Devika Murali Edakulathur",
        user_name: "devika",
        email: "devika@mailinator.com",
        password: password,
        role: "admin",
        is_verified: false,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: nanoid(),
        full_name: "Arjun S Kumar",
        user_name: "arjun",
        email: "arjun.s@mailinator.com",
        password: password,
        role: "admin",
        is_verified: false,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: nanoid(),
        full_name: "Joyal Thomas",
        user_name: "joyal",
        email: "joyal@mailinator.com",
        password: password,
        role: "admin",
        is_verified: false,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: nanoid(),
        full_name: "Frederic Thomson",
        user_name: "frederic",
        email: "frederic@mailinator.com",
        password: password,
        role: "admin",
        is_verified: false,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: nanoid(),
        full_name: "Jayakrishnan JR",
        user_name: "jayakrishnan",
        email: "jayakrishnan.jr@mailinator.com",
        password: password,
        role: "admin",
        is_verified: false,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: nanoid(),
        full_name: "Sajin Abdu",
        user_name: "sajin",
        email: "sajin@mailinator.com",
        password: password,
        role: "admin",
        is_verified: false,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: nanoid(),
        full_name: "Thalal Hassan Rahman R H",
        user_name: "thalal",
        email: "thalal.hassan@mailinator.com",
        password: password,
        role: "admin",
        is_verified: false,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: nanoid(),
        full_name: "Shiji George",
        user_name: "shiji",
        email: "shiji@mailinator.com",
        password: password,
        role: "admin",
        is_verified: false,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: nanoid(),
        full_name: "Shan KM",
        user_name: "shan",
        email: "shan.m@mailinator.com",
        password: password,
        role: "admin",
        is_verified: false,
        created_at: new Date(),
        updated_at: new Date(),
      },
      // {
      //   id: nanoid(),
      //   full_name: 'Jishnu N Bhattathiri',
      //   user_name:'jishnu',
      //   email:'jishnu.nb@neoito.com',
      //   password:password,
      //   role:'admin',
      //   is_verified:false,
      //   created_at:new Date(),
      //   updated_at:new Date(),
      // },
      // {
      //   id: nanoid(),
      //   full_name: 'Devika Murali Edakulathur',
      //   user_name:'devika',
      //   email:'devika@neoito.com',
      //   password:password,
      //   role:'admin',
      //   is_verified:false,
      //   created_at:new Date(),
      //   updated_at:new Date(),
      // },
      // {
      //   id: nanoid(),
      //   full_name: 'Arjun S Kumar',
      //   user_name:'arjun',
      //   email:'arjun.s@neoito.com',
      //   password:password,
      //   role:'admin',
      //   is_verified:false,
      //   created_at:new Date(),
      //   updated_at:new Date(),
      // },
      // {
      //   id: nanoid(),
      //   full_name: 'Joyal Thomas',
      //   user_name:'joyal',
      //   email:'joyal@neoito.com',
      //   password:password,
      //   role:'admin',
      //   is_verified:false,
      //   created_at:new Date(),
      //   updated_at:new Date(),
      // },
      // {
      //   id: nanoid(),
      //   full_name: 'Frederic Thomson',
      //   user_name:'frederic',
      //   email:'frederic@neoito.com',
      //   password:password,
      //   role:'admin',
      //   is_verified:false,
      //   created_at:new Date(),
      //   updated_at:new Date(),
      // },
      // {
      //   id: nanoid(),
      //   full_name: 'Jayakrishnan JR',
      //   user_name:'jayakrishnan',
      //   email:'jayakrishnan.jr@neoito.com',
      //   password:password,
      //   role:'admin',
      //   is_verified:false,
      //   created_at:new Date(),
      //   updated_at:new Date(),
      // },
      // {
      //   id: nanoid(),
      //   full_name: 'Sajin Abdu',
      //   user_name:'sajin',
      //   email:'sajin@neoito.com',
      //   password:password,
      //   role:'admin',
      //   is_verified:false,
      //   created_at:new Date(),
      //   updated_at:new Date(),
      // },
      // {
      //   id: nanoid(),
      //   full_name: 'Thalal Hassan Rahman R H',
      //   user_name:'thalal',
      //   email:'thalal.hassan@neoito.com',
      //   password:password,
      //   role:'admin',
      //   is_verified:false,
      //   created_at:new Date(),
      //   updated_at:new Date(),
      // },
      // {
      //   id: nanoid(),
      //   full_name: 'Shiji George',
      //   user_name:'shiji',
      //   email:'shiji@neoito.com',
      //   password:password,
      //   role:'admin',
      //   is_verified:false,
      //   created_at:new Date(),
      //   updated_at:new Date(),
      // },
      // {
      //   id: nanoid(),
      //   full_name: 'Shan KM',
      //   user_name:'shan',
      //   email:'shan.m@neoito.com',
      //   password:password,
      //   role:'admin',
      //   is_verified:false,
      //   created_at:new Date(),
      //   updated_at:new Date(),
      // }
    ],
  });
}

export default superAdmin;
